server.tomcat.additional-tld-skip-patterns=htmlunit-*.jar,jetty-*.jar

# Base de datos en memoria
spring.datasource.url=jdbc:hsqldb:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create

# Logging
logging.level.org.openxava=DEBUG
logging.level.com.openxava=DEBUG
logging.level.org.openxava.naviox=DEBUG
logging.level.com.openxava.naviox=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.openxava.naviox.web=DEBUG
logging.level.com.openxava.naviox.servlet=DEBUG
logging.level.org.openxava.web=DEBUG
logging.level.org.openxava.util=DEBUG

# Puerto
server.port=8080
naviox.defaultUserName=admin
naviox.defaultPassword=admin
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration